return {
  -- overrides `require("treesitter").setup(...)`
  ensure_installed = { 
      "awk",
      "bash",
      "cmake",
      "dockerfile",
      "dot",
      "gitattributes",
      "gitignore",
      "gitcommit",
      "git_rebase",
      "graphql",
      "help",
      "html",
      "http",
      "jq",
      "json",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "norg",
      "python",
      "regex",
      "rust",
      "sql",
      "terraform",
      "toml",
      "typescript",
      "yaml",
  },
}
