-- enable or disable highlighting for extra plugins
return {
  aerial = true,
  beacon = false,
  bufferline = true,
  cmp = true,
  dashboard = true,
  highlighturl = true,
  hop = false,
  indent_blankline = true,
  lightspeed = false,
  ["neo-tree"] = true,
  notify = true,
  ["nvim-web-devicons"] = true,
  rainbow = true,
  symbols_outline = false,
  telescope = true,
  treesitter = true,
  ["which-key"] = true,
}
